"""Tests for ``fastaiagent.multimodal.PDF``.

Real ``pymupdf`` throughout — no mocks. The fixture PDF is regenerated by
``tests/fixtures/multimodal/_make_fixtures.py`` and committed to the repo.
"""

from __future__ import annotations

import base64
from pathlib import Path

import pytest

from fastaiagent import PDF, Image
from fastaiagent._internal.errors import MultimodalError, UnsupportedFormatError

FIXTURES = Path(__file__).parent / "fixtures" / "multimodal"


def test_from_file_reads_bytes_and_records_path() -> None:
    pdf = PDF.from_file(FIXTURES / "contract.pdf")
    assert pdf.media_type == "application/pdf"
    assert pdf.source_path is not None
    assert pdf.source_path.endswith("contract.pdf")
    assert pdf.size_bytes() > 0


def test_page_count_is_two() -> None:
    pdf = PDF.from_file(FIXTURES / "contract.pdf")
    assert pdf.page_count() == 2


def test_extract_text_finds_known_phrases() -> None:
    pdf = PDF.from_file(FIXTURES / "contract.pdf")
    text = pdf.extract_text()
    assert "Service Agreement" in text
    assert "two years" in text


def test_to_page_images_renders_one_image_per_page() -> None:
    pdf = PDF.from_file(FIXTURES / "contract.pdf")
    pages = pdf.to_page_images(dpi=72)
    assert len(pages) == 2
    for page in pages:
        assert isinstance(page, Image)
        assert page.media_type == "image/png"
        assert page.size_bytes() > 0


def test_to_page_images_respects_max_pages_truncation(caplog: pytest.LogCaptureFixture) -> None:
    pdf = PDF.from_file(FIXTURES / "contract.pdf")
    with caplog.at_level("WARNING"):
        pages = pdf.to_page_images(dpi=72, max_pages=1)
    assert len(pages) == 1
    assert any("truncating" in rec.message for rec in caplog.records)


def test_from_bytes_round_trip() -> None:
    raw = (FIXTURES / "contract.pdf").read_bytes()
    pdf = PDF.from_bytes(raw)
    assert pdf.page_count() == 2
    assert pdf.source_path is None


def test_to_dict_from_dict_round_trip_preserves_bytes() -> None:
    pdf = PDF.from_file(FIXTURES / "contract.pdf")
    d = pdf.to_dict()
    assert d["type"] == "pdf"
    assert base64.b64decode(d["data_base64"]) == pdf.data
    pdf2 = PDF.from_dict(d)
    assert pdf2.data == pdf.data
    assert pdf2.source_path == pdf.source_path


def test_invalid_pdf_magic_raises() -> None:
    with pytest.raises(UnsupportedFormatError):
        PDF.from_bytes(b"this is not a pdf")


def test_empty_data_raises() -> None:
    with pytest.raises(MultimodalError):
        PDF.from_bytes(b"")


def test_from_url_rejects_file_scheme() -> None:
    with pytest.raises(UnsupportedFormatError):
        PDF.from_url("file:///tmp/nope.pdf")
