"""Tests for ``fastaiagent.multimodal.PDF``.

Real ``pypdfium2`` throughout — no mocks. The fixture PDF is regenerated by
``tests/fixtures/multimodal/_make_fixtures.py`` and committed to the repo.
"""

from __future__ import annotations

import base64
from pathlib import Path

import pytest

from fastaiagent import PDF, Image
from fastaiagent._internal.errors import MultimodalError, UnsupportedFormatError

FIXTURES = Path(__file__).parent / "fixtures" / "multimodal"


def test_from_file_reads_bytes_and_records_path() -> None:
    pdf = PDF.from_file(FIXTURES / "contract.pdf")
    assert pdf.media_type == "application/pdf"
    assert pdf.source_path is not None
    assert pdf.source_path.endswith("contract.pdf")
    assert pdf.size_bytes() > 0


def test_page_count_is_two() -> None:
    pdf = PDF.from_file(FIXTURES / "contract.pdf")
    assert pdf.page_count() == 2


def test_extract_text_finds_known_phrases() -> None:
    pdf = PDF.from_file(FIXTURES / "contract.pdf")
    text = pdf.extract_text()
    assert "Service Agreement" in text
    assert "two years" in text


def test_to_page_images_renders_one_image_per_page() -> None:
    pdf = PDF.from_file(FIXTURES / "contract.pdf")
    pages = pdf.to_page_images(dpi=72)
    assert len(pages) == 2
    for page in pages:
        assert isinstance(page, Image)
        assert page.media_type == "image/png"
        assert page.size_bytes() > 0


def test_to_page_images_respects_max_pages_truncation(caplog: pytest.LogCaptureFixture) -> None:
    pdf = PDF.from_file(FIXTURES / "contract.pdf")
    with caplog.at_level("WARNING"):
        pages = pdf.to_page_images(dpi=72, max_pages=1)
    assert len(pages) == 1
    assert any("truncating" in rec.message for rec in caplog.records)


def test_from_bytes_round_trip() -> None:
    raw = (FIXTURES / "contract.pdf").read_bytes()
    pdf = PDF.from_bytes(raw)
    assert pdf.page_count() == 2
    assert pdf.source_path is None


def test_to_dict_from_dict_round_trip_preserves_bytes() -> None:
    pdf = PDF.from_file(FIXTURES / "contract.pdf")
    d = pdf.to_dict()
    assert d["type"] == "pdf"
    assert base64.b64decode(d["data_base64"]) == pdf.data
    pdf2 = PDF.from_dict(d)
    assert pdf2.data == pdf.data
    assert pdf2.source_path == pdf.source_path


def test_invalid_pdf_magic_raises() -> None:
    with pytest.raises(UnsupportedFormatError):
        PDF.from_bytes(b"this is not a pdf")


def test_empty_data_raises() -> None:
    with pytest.raises(MultimodalError):
        PDF.from_bytes(b"")


# A payload with a valid ``%PDF-`` header (so ``__post_init__`` accepts it) but
# a body no parser can read — stands in for the customer's flat-compressed PDF.
_UNPARSEABLE_PDF = b"%PDF-1.4 not really a pdf at all"


def test_page_count_wraps_engine_failure() -> None:
    pdf = PDF.from_bytes(_UNPARSEABLE_PDF)
    with pytest.raises(MultimodalError, match="pdf_mode='native'"):
        pdf.page_count()


def test_extract_text_wraps_engine_failure() -> None:
    pdf = PDF.from_bytes(_UNPARSEABLE_PDF)
    with pytest.raises(MultimodalError, match="pdf_mode='native'"):
        pdf.extract_text()


def test_to_page_images_wraps_engine_failure() -> None:
    pdf = PDF.from_bytes(_UNPARSEABLE_PDF)
    with pytest.raises(MultimodalError, match="pdf_mode='native'"):
        pdf.to_page_images()


def test_from_url_rejects_file_scheme() -> None:
    with pytest.raises(UnsupportedFormatError):
        PDF.from_url("file:///tmp/nope.pdf")


def test_from_url_rejects_loopback_literal() -> None:
    """Regression for security_review_1.md C4: SSRF to 127.0.0.1."""
    with pytest.raises(MultimodalError, match="non-public|public address"):
        PDF.from_url("http://127.0.0.1:7842/secret.pdf")


def test_from_url_rejects_link_local_metadata_literal() -> None:
    """Regression for security_review_1.md C4: cloud-metadata SSRF."""
    with pytest.raises(MultimodalError, match="non-public|public address"):
        PDF.from_url("http://169.254.169.254/latest/meta-data/")


# --- render geometry (regression guard for the pypdfium2 port, 1.56.0) ---
#
# The engine swap away from AGPL-licensed pymupdf replaced the rasterizer, and
# the two libraries express resolution differently: pymupdf takes ``dpi=``
# directly, pypdfium2 takes a ``scale`` relative to PDF user space (72 units per
# inch). Getting that conversion wrong yields pages that still render — just at
# the wrong size — which no "does it run" check would catch. These pin the
# geometry that was verified pixel-identical against pymupdf before the swap.


@pytest.mark.parametrize(
    ("dpi", "expected"),
    [(72, (595, 842)), (150, (1240, 1755))],  # A4 at 72dpi; 595*150/72 = 1239.6 -> 1240
)
def test_page_render_size_matches_dpi(dpi: int, expected: tuple[int, int]) -> None:
    pages = PDF.from_file(FIXTURES / "contract.pdf").to_page_images(dpi=dpi)
    assert [p.dimensions() for p in pages] == [expected, expected]


def test_default_render_dpi_is_150() -> None:
    """``to_page_images()`` with no dpi must not silently change resolution."""
    page = PDF.from_file(FIXTURES / "contract.pdf").to_page_images(max_pages=1)[0]
    assert page.dimensions() == (1240, 1755)


def test_rendered_pages_differ_from_each_other() -> None:
    """Guards against every page rendering as page 1 — a plausible way to get
    an off-by-one wrong in a rasterizer port while sizes still look right."""
    pages = PDF.from_file(FIXTURES / "contract.pdf").to_page_images(dpi=72)
    assert pages[0].data != pages[1].data
