"""
Financial extraction demo — deep-research-agent applied to a SEC 10-K.

Showcases the **same Scope → parallel Research → Write pattern** from the
deep-research-agent template, but pointed at a financial document instead
of the open web. Pure composition over the existing primitives in
``topology.py`` — no new SDK code, no new classes, no new tables.

The 10-K excerpts in ``fixtures/apple_10k_fy2025_excerpts.txt`` were
downloaded from SEC.gov ahead of time. The ``search_filing`` tool defined
below greps that file. Researchers see a hermetic, deterministic corpus.

Run:
    cd examples/deep-research-agent
    python financial_demo.py            # uses fixtures/apple_10k_fy2025_excerpts.txt

Trace shape (identical to a normal deep-research run, with template kind
"financial-extraction" instead of "deep-research"):

    deep_research.session            ← template.kind="financial-extraction"
      ├── deep_research.scope        ← ResearchBrief
      ├── deep_research.research × N ← ResearchFindings per subtopic
      └── deep_research.write        ← Markdown table report
"""

from __future__ import annotations

import asyncio
import os
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

import fastaiagent as fa
from fastaiagent.agent.middleware import ToolBudget
from fastaiagent.trace import trace_context
from fastaiagent.trace.span import set_template_kind

import spans
from topology import (
    ResearchBrief,
    ResearchFindings,
    build_scope_agent,
    build_writer_agent,
    researcher_prompt,
)


_FIXTURE = Path(__file__).parent / "fixtures" / "apple_10k_fy2025_excerpts.txt"
_DOC = _FIXTURE.read_text() if _FIXTURE.exists() else ""


@fa.tool()
def search_filing(query: str) -> str:
    """Return paragraphs from the bundled 10-K matching the query.

    Drop-in replacement for ``web_search`` for the financial-extraction
    use case. Score paragraphs by token-overlap with the query, return
    the top 5. The fixture lives in ``fixtures/apple_10k_fy2025_excerpts.txt``
    and was downloaded from sec.gov ahead of time.
    """
    if not _DOC:
        return f"Filing fixture missing at {_FIXTURE}. Re-run the download step."
    q = {t.lower().strip(",.;:()$") for t in query.split() if len(t) > 3}
    if not q:
        return "Query had no useful tokens — try richer wording."
    scored: list[tuple[int, str]] = []
    for para in _DOC.split("\n\n"):
        if not para.strip():
            continue
        p_tokens = {t.lower().strip(",.;:()$") for t in para.split()}
        ov = len(q & p_tokens)
        if ov > 0:
            scored.append((ov, para))
    scored.sort(key=lambda x: -x[0])
    top = [p for _, p in scored[:5]]
    return "\n\n--- next match ---\n\n".join(top) or "No matches in filing."


def _researcher_llm() -> fa.LLMClient:
    return fa.LLMClient(
        provider=os.getenv("LLM_PROVIDER", "openai"),
        model=os.getenv("LLM_MODEL_RESEARCHER", "gpt-4o-mini"),
    )


def _build_local_researcher(subtopic: str, rationale: str) -> fa.Agent:
    """Like ``topology.build_researcher`` but tools = [search_filing]."""
    return fa.Agent(
        name=f"researcher:{subtopic[:40]}",
        system_prompt=researcher_prompt(subtopic, rationale),
        llm=_researcher_llm(),
        tools=[search_filing],
        middleware=[
            # Cash-flow extraction needs a few extra search rounds vs. the
            # web-research default — the cash-flow statement packs many
            # cross-referenced line items per question.
            ToolBudget(max_calls=15, message="Filing-search budget exhausted.")
        ],
        # Researchers do search→read→search→read loops over the bundled
        # filing; default ``max_iterations=10`` is too tight for 4 attrs
        # per branch. Bump explicitly. ToolBudget still caps actual fetches.
        config=fa.AgentConfig(max_iterations=20),
        output_type=ResearchFindings,
    )


TOPIC = """Extract Apple Inc's FY2025 financial snapshot from the 10-K filing
exposed via the search_filing tool. Capture exactly these 12 attributes,
each backed by a short quote from the filing:

  1. Total net sales (revenue)
  2. Gross margin (gross profit)
  3. Operating income
  4. Net income
  5. Diluted earnings per share
  6. Cash and cash equivalents (year-end)
  7. Total assets
  8. Total liabilities
  9. Cash generated by operating activities
 10. Number of full-time equivalent employees (period end)
 11. Fiscal year end date
 12. Research and development expense

Decompose the work so each subtopic agent owns ONE financial statement
section: income statement, balance sheet, cash flow statement, or
human-capital notes. The writer should produce a clear Markdown report
with each attribute's value (with units) and a citation drawn from the
filing text — not URLs, since the source is one bundled SEC 10-K."""


async def _scope() -> ResearchBrief:
    with trace_context("deep_research.scope") as span:
        result = await build_scope_agent().arun(TOPIC)
        brief = result.parsed
        if not isinstance(brief, ResearchBrief):
            raise RuntimeError(
                f"ScopeAgent did not return a ResearchBrief. "
                f"Got: {(result.output or '')[:200]!r}"
            )
        spans.set_brief(span, brief)
        return brief


async def _research_one(subtopic: str, rationale: str) -> ResearchFindings:
    with trace_context("deep_research.research") as span:
        spans.set_subtopic(span, subtopic)
        agent = _build_local_researcher(subtopic, rationale)
        result = await agent.arun(f"Research your assigned subtopic: {subtopic}")
        findings = result.parsed
        if not isinstance(findings, ResearchFindings):
            findings = ResearchFindings(
                subtopic=subtopic,
                summary=f"(researcher returned unstructured output: {(result.output or '')[:200]!r})",
                citations=[],
            )
        spans.set_findings(span, findings)
        return findings


async def _research_phase(brief: ResearchBrief) -> list[ResearchFindings]:
    return await asyncio.gather(
        *[_research_one(s.title, s.rationale) for s in brief.subtopics]
    )


def _writer_input(brief: ResearchBrief, findings: list[ResearchFindings]) -> str:
    parts = [
        f"# Research Brief\n\n**Topic:** {brief.topic}\n\n{brief.summary}\n",
        "## Findings by section\n",
    ]
    for f in findings:
        parts.append(f"### {f.subtopic}\n\n{f.summary}\n")
        if f.citations:
            parts.append("**Citations:**")
            for c in f.citations:
                parts.append(f"- {c.title}: {c.relevance}")
            parts.append("")
    parts.append(
        "Compose a Markdown report. Use a single table mapping each of the "
        "12 requested attributes to its value (with units) and a short "
        "citation quote drawn from the filing — not URLs, since the source "
        "is a single bundled SEC 10-K document."
    )
    return "\n".join(parts)


async def _write(brief: ResearchBrief, findings: list[ResearchFindings]) -> str:
    with trace_context("deep_research.write") as span:
        agent = build_writer_agent()
        result = await agent.arun(_writer_input(brief, findings))
        report = result.output if isinstance(result.output, str) else str(result.output)
        spans.set_report_metadata(span, report)
        return report


async def main() -> None:
    with trace_context("deep_research.session") as session_span:
        set_template_kind(session_span, "financial-extraction")
        spans.set_topic(session_span, "Apple Inc FY2025 financial snapshot")

        brief = await _scope()
        spans.set_plan(session_span, brief)
        print(f"\n[scope] {len(brief.subtopics)} subtopics:")
        for st in brief.subtopics:
            print(f"  • {st.title}")

        findings = await _research_phase(brief)
        print(
            f"\n[research] {sum(len(f.citations) for f in findings)} total citations "
            f"across {len(findings)} branches"
        )

        report = await _write(brief, findings)
        print("\n" + "=" * 70)
        print("FINAL REPORT")
        print("=" * 70)
        print(report)


if __name__ == "__main__":
    asyncio.run(main())
